#!/usr/bin/env python3
"""Generate the allowlisted native editing bridge from the retained SDEF.
No client-supplied source code or AppleScript property names are evaluated.
"""
import json
import sys
from pathlib import Path
import xml.etree.ElementTree as ET
ROOT = Path(__file__).resolve().parents[1]
root = ET.parse(ROOT / 'sdef/16.8.5.30.sdef').getroot()
classes = {c.attrib['name']: c for c in root.iter('class')}
enums = {e.attrib['name']: [v.attrib['name'] for v in e.findall('enumerator')] for e in root.iter('enumeration')}
scopes = {'adjustments': 'adjustment settings', 'lens': 'lens correction settings', 'layer': 'layer', 'luma': 'luma range settings', 'basicColor': 'basic color correction', 'advancedColor': 'advanced color correction'}
# Existing geometry API retains its containment/orientation safeguards.
geometry = {'orientation', 'rotation', 'flip', 'keystone amount', 'keystone vertical', 'keystone horizontal', 'keystone skew', 'keystone aspect'}
manifest = {}
for scope, cls in scopes.items():
    fields = []
    for p in classes[cls].findall('property'):
        name, typ = p.attrib['name'], p.attrib.get('type')
        if typ in ('adjustment settings', 'luma range settings', 'color editor options'): continue
        if typ not in ('real', 'integer', 'boolean', 'text', 'curve', 'RGB color') and typ not in enums: raise ValueError((scope, name, typ))
        fields.append(dict(name=name, type=typ, writable=p.attrib.get('access','rw') != 'r' and name not in geometry, values=enums.get(typ, []), route='geometry_set' if name in geometry else 'native_set'))
    manifest[scope] = fields
# Base-characteristics and LCC switches belong to the variant rather than adjustments.
manifest['variant'] = [dict(name=p.attrib['name'],type=p.attrib['type'],writable=True,values=enums.get(p.attrib['type'],[]),route='native_set') for p in classes['variant'].findall('property') if p.attrib['name'] in ('processing mode','LCC color cast','LCC dust removal','LCC uniform light','LCC uniform light amount')]
out = ROOT / 'Sources/CaptureOneCore/Resources'
def write(name, text):
    path = out / name
    if '--check' in sys.argv:
        if not path.exists() or path.read_text() != text: raise SystemExit('Generated native resource is stale: ' + str(path))
    else: path.write_text(text)
write('NativeEditing.json', json.dumps(manifest, indent=2)+'\n')
lines = ['-- Generated by scripts/generate-native-editing.py; do not edit.']
def emit(s): lines.append(s)
emit('''on nativeTarget(v, scopeName, layerNumber, elementNumber)
    tell application "/Applications/Capture One.app"
        set a to adjustments of v
        if layerNumber > 0 then set a to adjustments of layer layerNumber of v
        if scopeName is "adjustments" then return a
        if scopeName is "variant" then return v
        if scopeName is "lens" then return lens correction of v
        if scopeName is "layer" then return layer layerNumber of v
        if scopeName is "luma" then return luma range of layer layerNumber of v
        if scopeName is "basicColor" then return basic color correction elementNumber of color editor settings of a
        if scopeName is "advancedColor" then return advanced color correction elementNumber of color editor settings of a
    end tell
    error "Unknown native editing scope."
end nativeTarget

on nativeReadField(t, scopeName, fieldKey)
    tell application "/Applications/Capture One.app"''')
for scope, fields in manifest.items():
    emit(f'        if scopeName is "{scope}" then')
    for f in fields:
        n,t=f['name'],f['type']
        emit(f'            if fieldKey is "{n}" then')
        if t=='curve':
            emit(f'''                set pointValues to {{}}
                repeat with p in every curve point of {n} of t
                    set end of pointValues to (brightness of p as real)
                    set end of pointValues to (amount of p as real)
                end repeat
                return pointValues''')
        elif t=='RGB color': emit(f'                return {n} of t')
        else:
            emit(f'                set nativeValue to {n} of t')
            emit('                if nativeValue is missing value then return missing value')
            emit('                return nativeValue as '+('text' if t in enums else {'real':'real','integer':'integer','boolean':'boolean','text':'text'}[t]))
        emit('            end if')
    emit('        end if')
emit('''    end tell
    error "Unknown native field."
end nativeReadField

on nativeWriteField(t, scopeName, fieldKey, newValue)
    tell application "/Applications/Capture One.app"''')
for scope, fields in manifest.items():
    emit(f'        if scopeName is "{scope}" then')
    for f in fields:
        if not f['writable']: continue
        n,t=f['name'],f['type']
        emit(f'            if fieldKey is "{n}" then')
        if t=='curve':
            emit(f'''                set nativeStage to "begin"
                try
                    tell {n} of t
                        set nativeStage to "remove interior points"
                        repeat while (count of curve points) > 2
                            delete curve point 2
                        end repeat
                        set nativeStage to "first endpoint"
                        set brightness of first curve point to item 1 of newValue
                        set amount of first curve point to item 2 of newValue
                        set nativeStage to "last endpoint"
                        set brightness of last curve point to item -2 of newValue
                        set amount of last curve point to item -1 of newValue
                        set nativeStage to "insert interior point"
                        repeat with j from 3 to ((count of newValue) - 2) by 2
                            make new curve point with properties {{brightness:(item j of newValue), amount:(item (j + 1) of newValue)}}
                        end repeat
                    end tell
                on error msg number num
                    error ("{n}: " & nativeStage & ": " & msg) number num
                end try''')
        elif t in enums:
            for enum in enums[t]: emit(f'                if newValue is "{enum}" then set {n} of t to {enum}')
        else: emit(f'                set {n} of t to newValue')
        emit('                return true\n            end if')
    emit('        end if')
emit('''    end tell
    error "Native field is not writable."
end nativeWriteField

on nativeFieldNames(scopeName)''')
for scope, fields in manifest.items(): emit(f'    if scopeName is "{scope}" then return '+ '{'+', '.join(json.dumps(f['name']) for f in fields)+'}')
emit('    error "Unknown native scope."\nend nativeFieldNames')
emit('''on nativeLayers(v)
    set layerValues to {}
    tell application "/Applications/Capture One.app"
        repeat with l in every layer of v
            set end of layerValues to {nativeName:(name of l as text), nativeKind:(kind of l as text), nativeOpacity:(opacity of l as integer), nativeEnabled:(enabled of l as boolean)}
        end repeat
    end tell
    return layerValues
end nativeLayers

on nativeRead(docName, variantId, scopeName, layerNumber, elementNumber, expectedPath)
    set d to my checkedDocument(docName)
    tell application "/Applications/Capture One.app" to set v to variant id variantId of d
    my assertParent(v, expectedPath)
    set t to my nativeTarget(v, scopeName, layerNumber, elementNumber)
    set rows to {}
    repeat with k in my nativeFieldNames(scopeName)
        set keyText to k as text
        try
            set val to my nativeReadField(t, scopeName, keyText)
            set nums to missing value
            set txt to missing value
            set flag to missing value
            if val is missing value then
                -- A native unset layer adjustment is distinct from an unavailable property.
            else if class of val is boolean then
                set flag to val
            else if class of val is text then
                set txt to val
            else if class of val is list then
                set nums to val
            else
                set nums to {val as real}
            end if
            set end of rows to {fieldName:keyText, numbersVal:nums, textVal:txt, boolVal:flag, unavailable:missing value}
        on error msg number num
            if num is -1712 or num is -600 or num is -609 or num is -1743 then error msg number num
            set end of rows to {fieldName:keyText, numbersVal:missing value, textVal:missing value, boolVal:missing value, unavailable:(msg & " (" & num & ")")}
        end try
    end repeat
    set basicCount to 0
    set advancedCount to 0
    if scopeName is "adjustments" then
        tell application "/Applications/Capture One.app"
            set basicCount to count of basic color corrections of color editor settings of t
            set advancedCount to count of advanced color corrections of color editor settings of t
        end tell
    end if
    return {nativeRows:rows, nativeLayers:(my nativeLayers(v)), basicColorCount:basicCount, advancedColorCount:advancedCount}
end nativeRead

on nativeEqual(a, b)
    if a is missing value or b is missing value then return a is b
    if class of a is list and class of b is list then
        if (count of a) is not (count of b) then return false
        repeat with i from 1 to count of a
            if not my nativeEqual(item i of a, item i of b) then return false
        end repeat
        return true
    end if
    if (class of a is real or class of a is integer) and (class of b is real or class of b is integer) then
        return (a - b < 0.0001 and b - a < 0.0001)
    end if
    return a is b
end nativeEqual

on nativeApply(docName, variantId, scopeName, layerNumber, elementNumber, expectedPath, expectedFields, expectedValues, expectedLayerNames, patchKeys, patchValues)
    set d to my checkedDocument(docName)
    tell application "/Applications/Capture One.app" to set v to variant id variantId of d
    my assertParent(v, expectedPath)
    set actualLayerNames to {}
    repeat with l in my nativeLayers(v)
        set end of actualLayerNames to {nativeName of l, nativeKind of l, nativeOpacity of l, nativeEnabled of l}
    end repeat
    if actualLayerNames is not expectedLayerNames then error "Layers changed before dispatch." number -27002
    set t to my nativeTarget(v, scopeName, layerNumber, elementNumber)
    repeat with i from 1 to count of expectedFields
        set actual to my nativeReadField(t, scopeName, item i of expectedFields)
        if not my nativeEqual(actual, item i of expectedValues) then error "Native editing state changed before dispatch." number -27002
    end repeat
    repeat with i from 1 to count of patchKeys
        my nativeWriteField(t, scopeName, item i of patchKeys, item i of patchValues)
    end repeat
    return true
end nativeApply''')
write('NativeEditing.applescript', '\n'.join(lines)+'\n')
